### ISSUE TITLE
Add ability to link URLs on frontend with extra info already expanded

### ISSUE THREAD

**Issue by alexhaydock** [openrightsgroup/blocked-org-uk#380] opened 2019-03-12 10:36 UTC
It would be quite useful if I was able to link URLs to entries on Blocked.org.uk with the data about past blocks already expanded (i.e. as if someone had pre-clicked "Show all results")

For example I want to highlight this domain in the report: https://www.blocked.org.uk/site/http://a8c.com

But I want to draw attention not _just_ to the fact that there is a current block by Three, but also to the fact that there have been 4 previous blocks which have been cleared as a result of the report.

Maybe something like `?all=1` in the URL or similar?

**Comment by dantheta** [comment] 2019-05-27 14:18
I've added an `?expand=1` parameter to the site results page, eg:

https://www.blocked.org.uk/site/http://a8c.com?expand=1

**Comment by edjw** [comment] 2019-05-29 11:38
@dantheta – Can we make it a bit easier to discover this parameter? Maybe by overwriting the URL in the address bar when the 'Show all results' link is pressed?

**Comment by dantheta** [comment] 2019-05-29 15:37
No problem - I wasn't sure if this feature was intended for general use or just for Alex/admin.

I've added the expand parameter to the permalink when the full results are expanded.

**Comment by edjw** [comment] 2019-05-29 15:58
Brilliant, thanks Dan. Closing

**Closed as completed by edjw** 2019-05-29 15:58 UTC

**Comment by dantheta** [comment] 2019-05-29 15:59
Cheers!  The changes have just gone live, along with #393

**Comment by edjw** [comment] 2019-05-29 19:34
Is the addition of the expand parameter definitely working? Doesn't seem to be working for me on Firefox or Chrome

**Comment by dantheta** [comment] 2019-05-29 21:26
It's working for me in Firefox & Chromium (Linux)

**Comment by edjw** [comment] 2019-05-30 10:30
GIF showing what's happening for me

![CleanShot 2019-05-30 at 11 29 06](https://user-images.githubusercontent.com/6547979/58627077-3f657b80-82ce-11e9-8c9e-bebdfdca98ec.gif)

**Comment by dantheta** [comment] 2019-05-30 22:22
The URL updating is there now (for the "show all results" toggle).

**Comment by dantheta** [comment] 2019-05-31 07:57
Ah, got it. I was changing the permalink URL at the bottom in response to the expand event. I'll fix it for the address bar URL as well. Sorry!

On 30 May 2019 11:30:10 BST, edjw <notifications@github.com> wrote:
>![CleanShot 2019-05-30 at 11 29
>06](https://user-images.githubusercontent.com/6547979/58627077-3f657b80-82ce-11e9-8c9e-bebdfdca98ec.gif)
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/openrightsgroup/blocked-org-uk/issues/380#issuecomment-497284564

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
